# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: AIGISSS #网站标题
subtitle: 爱即是诗 #网站副标题
description: 真正的伟大,即在于以脆弱的凡人之躯而具有神性的不可战胜。
author: Gong
language: zh-CN #主题文件名称
timezone:

# URL  #绑定域名
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.aigisss.com
root: /
# permalink: :year/:month/:day/:title/
# permalink_defaults:
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32 # 算法：crc16(default) and crc32
  rep: hex # 进制：dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - lab/**
  - photo/**
# Writing 文章布局，写作格式
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination 每页文章数
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next #主题

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: https://github.com/Cenergy/cenergy.github.io.git
    coding: https://git.dev.tencent.com/AIGIS/aigis.git
  branch: master

duoshuo:
  enable: false
  shortname: your-duoshuo-shortname

#启动搜索功能
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# add post views
leancloud_visitors:
  enable: true
  app_id: nRhgx6rQY4BBWbmWGnc4ftDE-gzGzoHsz
  app_key: yciTpXUYAqqMCPXM3dzOvEaX
# 自动生成sitemap
sitemap:
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml

# Security
##
encrypt:
  enable: true

# 代码高亮显示
# highlight:
#   enable: true
#   line_number: true
#   auto_detect: false
#   tab_replace:
highlight:
  enable: false

prism_plugin:
  mode: "preprocess" # realtime/preprocess
  theme: "atom-dark"
  line_number: false # default false
  custom_css: "" # optional

# 文章字数和阅读时长
# symbols_count_time:
#   #文章内是否显示
#   symbols: true
#   time: true
#   # 网页底部是否显示
#   total_symbols: true
#   total_time: true

# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
    - "google078dd53431bb11ee.html"
# 压缩css
neat_css:
  enable: true
  exclude:
    - "**/*.min.css"
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "**/*.min.js"
    - "**/jquery.fancybox.pack.js"
    - "**/index.js"
    - "**/love.js"
    - "**/**min.js"
# 压缩博文配置结束

robotstxt:
  useragent: "*"
  disallow:
    - /admin/
    - /vendors/
    - /js/
    - /css/
    - /fonts/
    - /fancybox/
    - /fonts/
    - .js$
    - .css$
    - .jpg$
    - .jpeg$
    - .gif$
    - .png$
    - .bmp$
  allow:
    - /
    - /archives/
    - /categories/
    - /tags/
  sitemap: /sitemap.xml
